server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/Desktop/config-repo
#          uri: git@github.com:config-.git
#          ignoreLocalSshSettings: true
#          privateKey: |
#                       -----BEGIN RSA PRIVATE KEY-----
#                       -----END RSA PRIVATE KEY-----
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  jackson:
#    property-naming-strategy: SNAKE_CASE

security:
  user:
    name: root
    password: s3cr3t

logging:
  level:
    org.springframework.cloud: debug
