#server:
#  port: ${PORT:9999}
#  context-path: /uaa
#  use-forward-headers: false
#
#
#spring:
#  application:
#    name: auth-server
#
#security:
#  basic:
#    enabled: false
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#
#logging:
#  level:
#    org.springframework.security: TRACE



server:
  port: 8081
#  context-path: /auth

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth2
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
#  thymeleaf:
#    cache: false
#    check-template: true
#    check-template-location: true
#    content-type: text/html
#    enabled: true
#    encoding: UTF-8
#    mode: HTML
#    prefix: classpath:/templates/
#    suffix: .html

security:
  basic:
    enabled: false
  sessions: if-required

logging:
  level:
    org.springframework.security: TRACE