#spring:
#  aop:
#    proxyTargetClass: true
#  application:
#    name: api-gateway
#
## Define the port where the API gateway server would be running
#server:
#  port: 8084
#
## Define the Eureka server that handles service registration
#eureka:
#  instance:
#      hostname: localhost
#      port: 8761
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
#
#zuul:
#  routes:
#    dummy-service: /dummy/**
#    auth-server:
#      sensitiveHeaders:
#      path: /uaa/**
#      stripPrefix: false
#  add-proxy-headers: true
#
#security:
#  # Disable Spring Boot basic authentication
#  basic:
#    enabled: false
#  oauth2:
#    sso:
#      loginPath: /login
#    client:
#      accessTokenUri: http://uaa-service/uaa/oauth/token
#      userAuthorizationUri: http://localhost:8084/uaa/oauth/authorize
#      clientId: acme
#      clientSecret: acmesecret
#    resource:
##      jwt:
##        keyValue: |
##          -----BEGIN PUBLIC KEY-----
##          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
##          -----END PUBLIC KEY-----
##      id: openid
##      serviceId: ${PREFIX:}resource
#      userInfoUri: http://localhost:8084/uaa/user/me
#
#logging:
#  level.org.springframework.security: DEBUG


server:
    port: 8084

zuul:
  routes:
    ui-client:
      sensitiveHeaders:
      path: /ui/**
      url: http://localhost:8080/ui
    auth-server:
      sensitiveHeaders:
      path: /auth/**
      url: http://localhost:8081/auth

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8081/auth/oauth/token
      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
    resource:
      userInfoUri: http://localhost:8081/auth/user/me
  sessions: ALWAYS

spring:
  thymeleaf:
    cache: false

logging:
  level.org.springframework.security: DEBUG