server:
  port: 8888

spring:
#  profiles:
#    active: native
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#  jackson:
#    property-naming-strategy: SNAKE_CASE

security:
  user:
    name: root
    password: s3cr3t