spring:
  application:
    name: uaa-service
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html

server:
  port: 8769
  context-path: /uaa
  use-forward-headers: false

eureka:
  instance:
    hostname: localhost
    port: 8761

security:
  basic:
    enabled: false
  user:
    password: password
  ignored: /css/**,/js/**,/favicon.ico,/webjars/**

logging:
  level.org.springframework.security: DEBUG
